apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.host }}
  dnsNames:
  - {{ .Values.host }}