apiVersion: apps/v1
kind: Deployment
metadata:
  name: minilytics
  namespace: {{ .Values.namespace }}
  labels:
    app: minilytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minilytics
  template:
    metadata:
      labels:
        app: minilytics
    spec:
      containers:
      - name: minilytics
        image: cfe84/minilytics
        env:
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: minilytics-secrets
              key: STORAGE_CONNECTION_STRING
        - name: TABLE_NAME
          valueFrom:
            secretKeyRef:
              name: minilytics-secrets
              key: TABLE_NAME

---

kind: Service
apiVersion: v1
metadata:
  name: minilytics-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: minilytics
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  externalTrafficPolicy: Local
