apiVersion: v1    
kind: Secret
metadata:
  name: minilytics-secrets 
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  STORAGE_CONNECTION_STRING: {{ .Values.storageConnectionString | b64enc }}
  TABLE_NAME: {{ .Values.tableName | b64enc}}